version: "3.8"

services:
  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    extends:
      file: ../backend/docker-compose.yml
      service: backend
