version: '3'

services:
  db:
    env_file:
      - .env
    container_name: ${DB_NAME}
    image: postgres:bookworm
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_UNIX_PORT: ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  app:
    env_file:
      - .env
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: video-management
    environment:
      PORT: ${PORT}
      DB_HOST: db
      ENV: production
    ports:
      - '3000:${PORT}'
    volumes:
      - ./docker/app:/app/src
    restart: always
    